### ISSUE TITLE
Build issues on caddyserver.com

### ISSUE THREAD

**Issue by magikstm** [casbin/caddy-authz#1]
I believe the issue could be corrected by using a valid release version tag in the form `v0.1.0` or `v1.0.0`.

Ref: https://caddy.community/t/plugins-having-build-issues-as-of-05-06-2019/5817

**Comment by hsluoyz** [comment]
Hi @magikstm , can you help make a PR?

UPDATE
======

Is this as simple as I release the ``v1.0.0`` version of this project at GitHub? If yes, I can do it now.

**Comment by magikstm** [comment]
I believe it is as simple as releasing v1.0.0 of the plugin then making it visible on the Caddy build server.

**Comment by magikstm** [comment]
Ref: https://caddy.community/t/plugin-authors-please-deploy-at-semantic-version-tags-or-specific-commits/5795

**Comment by hsluoyz** [comment]
Hi @magikstm , I have released ``v1.0.0``: https://github.com/casbin/caddy-authz/releases/tag/v1.0.0

What do you mean by "making it visible on the Caddy build server"? I think this project is open-source and the release is already visible to anyone including the Caddy build server, right?

**Comment by magikstm** [comment]
I think you would need to deploy the release in your developer portal account.

Ref: https://github.com/mholt/caddy/wiki/Publishing-a-Plugin-to-the-Download-Page

Link: https://caddyserver.com/account/login

**Comment by hsluoyz** [comment]
I have released `v1.0.1``:

![image](https://user-images.githubusercontent.com/3787410/59006795-5835da00-8856-11e9-90ba-3c3d277ce978.png)

Thanks for the PR!
