### ISSUE TITLE
Add caddy-authz to the official Caddy v2 code & Caddy v2 docs's module list

### ISSUE THREAD

**Issue by hsluoyz** [casbin/caddy-authz#10]
For Caddy v1, I used to make such a PR: https://github.com/caddyserver/caddy/pull/1693 which registered caddy-authz as "authz" plugin in the Caddy v1 ecosystem.

But Caddy comes to v2 now and all v1 code is gone. We need to follow a similar path to integrate caddy-authz into Caddy v2 code-base again.

Meanwhile, the v1 docs is also gone. The current v2 docs's module list has no our middleware any more: https://caddyserver.com/docs/modules/

We also need to make PR to that website's source code: https://github.com/caddyserver/website to add our middleware.

**Comment by 00LT00** [comment]
May be I can take it after exam

**Comment by hsluoyz** [comment]
@closetool this can be our next step.

**Comment by hsluoyz** [comment]
@closetool 

Our module name is `http.handlers.authz`:

https://github.com/casbin/caddy-authz/blob/6cb348ced3f4fdebab3a600f4dd0ab9347b2b99f/authz.go#L28-L34

We should follow the docs page for another module: https://caddyserver.com/docs/modules/http.handlers.auth_portal , make a PR to that website's source code: https://github.com/caddyserver/website to add our middleware.

**Comment by hsluoyz** [comment]
@closetool I saw your issue (https://github.com/caddyserver/website/issues/132) and this: https://caddyserver.com/docs/modules/http.handlers.authz it's great!

But can we add the missing text?

![image](https://user-images.githubusercontent.com/3787410/106379025-115e0600-63e4-11eb-8faa-6f32d9f95465.png)

![image](https://user-images.githubusercontent.com/3787410/106379019-04411700-63e4-11eb-9305-dff28729f7f4.png)

**Comment by hsluoyz** [comment]
@closetool ok, saw the comments here (https://github.com/caddyserver/website/issues/132#issuecomment-770335304), let's just wait though, closed here.

Well done!
