### ISSUE TITLE
caddy v2 support

### ISSUE THREAD

**Issue by SvenDowideit** [casbin/caddy-authz#5]
I wonder if caddy v2 support is something someone's working on

**Comment by hsluoyz** [comment]
@nodece @GopherJ @dovics @00LT00 can anyone take this issue?

**Comment by 00LT00** [comment]
Thanks for your report.We will update the version in the near future

**Comment by 00LT00** [comment]
We update the casbin from v2.0.1 to v2.8.6 and the caddy from v1.0.1 to v1.0.5 in this [pull request](https://github.com/casbin/caddy-authz/pull/6#issue-456312718) @SvenDowideit

**Comment by SvenDowideit** [comment]
@00LT00 that's for caddy version 1 - I'm curious about caddy version 2 support

**Comment by hsluoyz** [comment]
@00LT00 please fix it.

**Comment by 00LT00** [comment]
@SvenDowideit update caddy from v1 to v2. #7

**Comment by hsluoyz** [comment]
@SvenDowideit v2.0.0 has been released: https://github.com/casbin/caddy-authz/releases/tag/v2.0.0
