### ISSUE TITLE
Revisit a merged PR which broke our Travis CI and the support for Caddy v2

### ISSUE THREAD

**Issue by hsluoyz** [casbin/caddy-authz#8]
See details at: https://github.com/casbin/caddy-authz/pull/7#issuecomment-757506634

**Comment by hsluoyz** [comment]
@closetool can you work on this?

**Comment by kilosonc** [comment]
ok, I'll try to fix it

**Comment by kilosonc** [comment]
I guess the go version in travis.yml should be 1.14.x at least
![image](https://user-images.githubusercontent.com/52988625/104278704-fcc4d700-54e3-11eb-8294-3f4dec2f4bd5.png)
and the coveralls service should be opened

**Comment by hsluoyz** [comment]
@closetool coveralls is enabled: https://coveralls.io/github/casbin/caddy-authz?branch=master

**Comment by kilosonc** [comment]
@hsluoyz yes, but some packages require go version over 1.14 like github.com/caddyserver/certmagic

**Comment by hsluoyz** [comment]
@closetool good to know!

Please make a PR to fix the Go versions here: https://github.com/casbin/caddy-authz/blob/master/.travis.yml#L6

We usually test against several popular Go versions including tip. Please refer to Go Casbin repo for it.

**Comment by hsluoyz** [comment]
@closetool merged: https://github.com/casbin/caddy-authz/pull/9

**Comment by hsluoyz** [comment]
@closetool good to see CI recovered! But I saw the code coverage has dropped to 0%, can you investigate why?

![image](https://user-images.githubusercontent.com/3787410/104314820-edaa4d00-5514-11eb-902a-e67d20dec1ed.png)


https://coveralls.io/github/casbin/caddy-authz?branch=master

![image](https://user-images.githubusercontent.com/3787410/104314874-0286e080-5515-11eb-9311-7bba23c668f7.png)

**Comment by kilosonc** [comment]
sure

**Comment by kilosonc** [comment]
@hsluoyz I compared v2.0.0 and v1.0.2, and I found there's no ``authz_test.go`` in v2.0.0
perhaps that's why coverage dropped to 0%

**Comment by hsluoyz** [comment]
good found! I think this PR: https://github.com/casbin/caddy-authz/pull/7/files deleted `authz_test.go`. We need to add it back and make it right in the new Caddy v2 scenario, as our code needs testing to make it behave as expected.

![image](https://user-images.githubusercontent.com/3787410/104317830-7925dd00-5519-11eb-8d3b-9c4447acdc1e.png)

**Comment by kilosonc** [comment]
ok, I'll work on it
